### PR TITLE
Some enhanements

### PR DESCRIPTION
**Pull request by Rafkev**
In enhancing my Dev brother and friend's work, I made several improvements to improve functionality, security, and user experience as listed below:

**Prevent Division by Zero:** Add a check to prevent division by zero, which can lead to errors.

**Handle Key Press Events:** Allow users to input calculations using keyboard keys.

**Improve Error Handling:** Provide more informative error messages for better user feedback.

**Styling Improvements:** Enhance the appearance of the calculator for better visual appeal.

Let's integrate these enhancements into the code:

### CODE REVIEW

**Comment by Rafkev** [comment]
Please, dev bro check it out.

**Comment by uwakevwe** [comment]
Great man

**Comment by Rafkev** [comment]
Great man too

**Review by Rafkev — COMMENTED** [review]
Code works

**Pull request merged**
